// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as LoginWeb3 from "../components/LoginWeb3.bs.js";

function App(Props) {
  return React.createElement("div", undefined, React.createElement(LoginWeb3.make, {}));
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
